export const conversations = [
  {
    ticketId: "TKT-001",
    title: "Login page not loading on mobile",
    category: "Technical",
    status: "open",
    messages: [
      {
        id: 1,
        sender: "user",
        name: "Rahul Mehta",
        text: "Hi, I am unable to load the login page on my iPhone. It just shows a blank white screen.",
        time: "09:12 AM",
        date: "2026-04-10",
      },
      {
        id: 2,
        sender: "portal",
        name: "Support Team",
        text: "Hello Rahul! Thank you for reaching out. Could you please share which iOS version you are using and which browser you tried?",
        time: "09:15 AM",
        date: "2026-04-10",
      },
      {
        id: 3,
        sender: "user",
        name: "Rahul Mehta",
        text: "I am on iOS 16.5 and tried both Safari and Chrome. Same issue on both.",
        time: "09:18 AM",
        date: "2026-04-10",
      },
      {
        id: 4,
        sender: "portal",
        name: "Support Team",
        text: "Thank you for the details. We have identified a compatibility issue with iOS 16.x. Our engineering team is working on a fix. As a workaround, please try clearing your browser cache and reloading.",
        time: "09:25 AM",
        date: "2026-04-10",
      },
      {
        id: 5,
        sender: "user",
        name: "Rahul Mehta",
        text: "Clearing cache did not help. Still the same blank screen.",
        time: "09:30 AM",
        date: "2026-04-10",
      },
      {
        id: 6,
        sender: "portal",
        name: "Support Team",
        text: "We understand the inconvenience. Our team has escalated this to Priority 1. You will receive an update within 2 hours. We apologise for the disruption.",
        time: "09:35 AM",
        date: "2026-04-10",
      },
    ],
  },
  {
    ticketId: "TKT-002",
    title: "March invoice not generated",
    category: "Billing",
    status: "in_progress",
    messages: [
      {
        id: 1,
        sender: "user",
        name: "Priya Sharma",
        text: "Hello, our March invoice has not been generated yet. It is already the 11th of April. This is causing issues with our finance team.",
        time: "11:00 AM",
        date: "2026-04-11",
      },
      {
        id: 2,
        sender: "portal",
        name: "Billing Team",
        text: "Hi Priya, we are sorry for the delay. Could you please confirm your client account ID so we can look into this immediately?",
        time: "11:05 AM",
        date: "2026-04-11",
      },
      {
        id: 3,
        sender: "user",
        name: "Priya Sharma",
        text: "Sure, our account ID is JFL-2024-009.",
        time: "11:07 AM",
        date: "2026-04-11",
      },
      {
        id: 4,
        sender: "portal",
        name: "Billing Team",
        text: "Thank you Priya. We can see your account. It appears the invoice was stuck due to a billing cycle sync issue. We are generating it manually right now.",
        time: "11:15 AM",
        date: "2026-04-11",
      },
      {
        id: 5,
        sender: "user",
        name: "Priya Sharma",
        text: "Thank you. How long will it take?",
        time: "11:17 AM",
        date: "2026-04-11",
      },
      {
        id: 6,
        sender: "portal",
        name: "Billing Team",
        text: "The invoice will be emailed to your registered address within the next 30 minutes. We will also attach it in this ticket thread once done.",
        time: "11:20 AM",
        date: "2026-04-11",
      },
      {
        id: 7,
        sender: "user",
        name: "Priya Sharma",
        text: "Great, thank you for the quick response!",
        time: "11:22 AM",
        date: "2026-04-11",
      },
    ],
  },
  {
    ticketId: "TKT-003",
    title: "Request for dark mode",
    category: "Feature Request",
    status: "open",
    messages: [
      {
        id: 1,
        sender: "user",
        name: "Anil Kumar",
        text: "Hi team, we would love to have a dark mode option in the customer portal. Many of our users work late hours and it would really help reduce eye strain.",
        time: "02:00 PM",
        date: "2026-04-12",
      },
      {
        id: 2,
        sender: "portal",
        name: "Product Team",
        text: "Hi Anil! That is a great suggestion. We have actually received similar requests from a few other clients as well. Could you share more about how your team would use it — always on, scheduled, or system-preference based?",
        time: "02:10 PM",
        date: "2026-04-12",
      },
      {
        id: 3,
        sender: "user",
        name: "Anil Kumar",
        text: "Ideally a toggle would be perfect so each user can choose. But following the system preference would also work for us.",
        time: "02:15 PM",
        date: "2026-04-12",
      },
      {
        id: 4,
        sender: "portal",
        name: "Product Team",
        text: "Understood! We will log this as a feature request with your input. Our product team reviews these in our quarterly planning. We will keep you updated on the roadmap.",
        time: "02:20 PM",
        date: "2026-04-12",
      },
      {
        id: 5,
        sender: "user",
        name: "Anil Kumar",
        text: "Sounds good. Looking forward to it. Also, is there any way to upvote this request or see if others have raised it too?",
        time: "02:25 PM",
        date: "2026-04-12",
      },
      {
        id: 6,
        sender: "portal",
        name: "Product Team",
        text: "We do not have a public roadmap vote yet, but your feedback has been noted with high priority. We will reach out once this feature is on our development sprint. Thank you for the detailed input!",
        time: "02:30 PM",
        date: "2026-04-12",
      },
    ],
  },
];

export const statusColors = {
  open: { bg: "#e3f2fd", text: "#1565c0" },
  in_progress: { bg: "#fff8e1", text: "#f57f17" },
  resolved: { bg: "#e8f5e9", text: "#2e7d32" },
  closed: { bg: "#f5f5f5", text: "#616161" },
};
